{% set weekly_textbook_topics = [
{week: "1"},
{week: "2"},
  {name: "Java"},
    {heading: "Java: Intro"},
      {location: ["cppToJava", "about"]},
      {location: ["cppToJava", "javaWorld", "what"]},
      {location: ["cppToJava", "javaWorld", "how"], panopto: "eb1fbc9c-25bf-4f71-aa2e-ac0700d2eab6"},
      {location: ["cppToJava", "javaWorld", "editions"]},
    {heading: "Java: HelloWorld", panopto: "2272aac8-8865-4f83-8c18-ac0c00bec829"},
      {location: ["cppToJava", "gettingStarted", "installation"]},
      {location: ["cppToJava", "gettingStarted", "helloWorld"]},
      {location: ["cppToJava", "gettingStarted", "compiling"]},
      {location: ["cppToJava", "gettingStarted", "running"]},
    {heading: "Java: Data Types"},
      {location: ["cppToJava", "dataTypes", "primitiveTypes"]},
      {location: ["cppToJava", "dataTypes", "variables"]},
      {location: ["cppToJava", "dataTypes", "operators"]},
      {location: ["cppToJava", "dataTypes", "arrays"]},
    {heading: "Java: Control Flow"},
      {location: ["cppToJava", "controlFlow", "branching"]},
      {location: ["cppToJava", "controlFlow", "methods"]},
      {location: ["cppToJava", "controlFlow", "loops"]},
  {name: "OOP + Java"},
    {heading: "OOP: Classes and Objects"},
      {location: ["oop", "introduction", "what"], panopto: "555275b7-e203-4405-8501-ac0c00c81fbf"},
      {location: ["oop", "objects", "what"], panopto: "5ab57a96-01e3-46e5-ab5a-ac0c00cb212f"},
      {location: ["oop", "objects", "abstraction"], panopto: "4b95c852-d083-422c-9853-ac0c00cd8074"},
      {location: ["oop", "objects", "encapsulation"], panopto: "d9f2b2b6-35ab-436e-8eee-ac0c00d3faf1"},
      {location: ["oop", "classes", "what"], panopto: "bb296210-fcac-4feb-9668-ac0c00d6de6e"},
    {heading: "Java: Objects", panopto: "c9dfeadd-edc1-40f9-b138-ac0e00955f54"},
      {location: ["cppToJava", "objects", "usingObjects"]},
      {location: ["cppToJava", "objects", "instanceMembers"]},
      {location: ["cppToJava", "objects", "passingObjects"]},
      {location: ["cppToJava", "objects", "garbageCollection"]},
    {heading: "Java: Classes", panopto: "b8096405-2cef-4ef4-83a2-ac0e009b6ed3"},
      {location: ["cppToJava", "classes", "definingClasses"]},
      {location: ["cppToJava", "classes", "gettersAndSetters"]},
  {name: "Revision Control"},
    {heading: "RCS: Init, Commit"},
      {location: ["revisionControl", "what"]},
      {location: ["revisionControl", "repositories"]},
      {location: ["gitAndGithub", "init"], panopto: "b5ca72a1-8366-4971-a523-ac090090f68b"},
      {location: ["revisionControl", "savingHistory"]},
      {location: ["gitAndGithub", "commit"], panopto: "8f288870-1d75-4218-94fe-ac0900a026de"},
      {location: ["gitAndGithub", "ignore"], panopto: "47b7180e-9acb-4fc7-8ad7-ac0900a53544"},
    {heading: "RCS: Remote Repos"},
      {location: ["revisionControl", "remoteRepositories"], panopto: "d5c79357-9778-4cf7-8e5d-ac0900c337ae"},
      {location: ["gitAndGithub", "clone"], panopto: "3bcdcf56-7456-46e3-a163-ac0900d28d6e"},
      {location: ["gitAndGithub", "fork"], panopto: "76879d62-2bb4-4951-a3d3-ac0900c68689"},
      {location: ["gitAndGithub", "push"], panopto: "897e2c87-2add-454c-8e2b-ac0900d8006f"},
    {heading: "RCS: Using History"},
      {location: ["revisionControl", "usingHistory"]},
      {location: ["gitAndGithub", "tag"], panopto: "9f40b219-58d7-4192-8ec8-ac0900a64410"},
      {location: ["gitAndGithub", "diff"], panopto: "cccc7475-1bfa-4d88-8e2f-ac0900a8dbd2"},
      {location: ["gitAndGithub", "checkout"], panopto: "f16e2d7f-5f78-455c-830e-ac0900b7a747"},
      {location: ["gitAndGithub", "stash"], panopto: "683017df-21c8-4890-8c42-ac0900c15bf4"},
  {name: "Implementation"},
    {heading: "IDEs: Basic Features"},
      {location: ["ides", "introduction", "what"]},
      {location: ["intellij", "projectSetup"]},
      {location: ["intellij", "codeNavigation"]},
{week: "3"},
  {name: "OOP in Java"},
    {heading: "OOP, Java: Class-Level Members"},
      {location: ["oop", "classes", "classLevelMembers"], panopto: "02da6f70-2dd8-4093-867e-ac1a00d47ad9"},
      {location: ["cppToJava", "classes", "classLevelMembers"], panopto: "73060fc7-4c2d-4a03-bb8e-ac0e00c9a8fe"},
    {heading: "Java: Useful Classes"},
      {location: ["reuse", "apis", "what"]},
      {location: ["cppToJava", "usefulClasses", "api"], panopto: "0e3387ea-9d32-4d29-8b3f-ac1b008a330c"},
      {location: ["cppToJava", "usefulClasses", "stringClass"], panopto: "9946e494-b476-4ca7-aede-ac1b008e9f4c"},
      {location: ["cppToJava", "usefulClasses", "wrapperClasses"], panopto: "8f1d521c-ed9d-482b-b912-ac1b00901f69"},
      {location: ["cppToJava", "usefulClasses", "arraysClass"], panopto: "babddd5f-0acb-437f-9d8e-ac1b0091ef29"},
      {location: ["cppToJava", "usefulClasses", "scannerClass"], panopto: "1d7b7e27-5ef1-41db-a777-ac1b0092b71c"},
    {heading: "OOP + Java: Inheritance"},
      {location: ["oop", "inheritance", "what"]},
      {location: ["oop", "inheritance", "overloading"]},
      {location: ["oop", "inheritance", "overriding"]},
      {location: ["cppToJava", "inheritance", "basic"]},
      {location: ["cppToJava", "inheritance", "objectClass"]},
    {heading: "OOP + Java: Polymorphism"},
      {location: ["oop", "polymorphism", "what"]},
      {location: ["oop", "inheritance", "substitutability"]},
      {location: ["oop", "inheritance", "dynamicAndStaticBinding"]},
      {location: ["oop", "polymorphism", "how"]},
      {location: ["cppToJava", "inheritance", "polymorphism"]},
    {heading: "Java: Constants"},
      {location: ["cppToJava", "misc", "constants"]},
    {heading: "OOP + Java: Enumerations"},
      {location: ["oop", "classes", "enumerations"]},
      {location: ["cppToJava", "misc", "enums"]},
  {name: "Implementation"},
    {heading: "Code Quality: Coding Standards"},
      {location: ["codeQuality", "introduction", "basic"], panopto: "e2ab97ac-e79c-4555-96cc-ac0e00dc8a73"},
      {location: ["codeQuality", "followStandard", "introduction"], panopto: "0c8f7805-d88a-4845-a530-aca700c95891"},
  {name: "Revision Control"},
    {heading: "RCS: Fetch, Pull, Pull Requests"},
      {location: ["gitAndGithub", "pull"], panopto: "3dbac71a-f450-47b6-8f4e-ac0900d765fe"},
      {location: ["gitAndGithub", "createPRs"]},
  {name: "Testing"},
    {heading: "Automated Testing of Text UIs"},
      {location: ["testing", "introduction", "what"], panopto: "48b60ad5-387d-4d2d-a82a-ac0c0091a705"},
      {location: ["testing", "testingTypes", "regressionTesting", "what"], panopto: "fc0416bd-b376-417d-9e45-ac0c00a53312"},
      {location: ["testing", "testAutomation", "what"]},
      {location: ["testing", "testAutomation", "testingTextUis"], panopto: "438a3ad8-a4a5-41ae-9683-ac0c00b25978"},
{week: "4"},
  {name: "OOP + Java"},
    {heading: "Java: Casting"},
      {location: ["cppToJava", "misc", "casting"]},
    {heading: "OOP + Java: Abstract Classes"},
        {location: ["oop", "inheritance", "abstractClasses"]},
        {location: ["cppToJava", "inheritance", "abstractClassesAndMethods"]},
    {heading: "OOP + Java: Interfaces"},
        {location: ["oop", "inheritance", "interfaces"]},
        {location: ["cppToJava", "inheritance", "interfaces"]},
    {heading: "Java: Packages"},
      {location: ["cppToJava", "misc", "packages"]},
    {heading: "Java: Access Modifiers"},
      {location: ["cppToJava", "misc", "accessModifiers"]},
  {name: "Implementation"},
    {heading: "Error Handling: Exceptions"},
      {location: ["errorHandling", "introduction", "what"]},
      {location: ["errorHandling", "exceptions", "what"]},
      {location: ["errorHandling", "exceptions", "how"]},
      {location: ["cppToJava", "exceptions", "what"]},
      {location: ["cppToJava", "exceptions", "how"]},
      {location: ["errorHandling", "exceptions", "when"]},
    {heading: "Code Quality: Naming"},
      {location: ["codeQuality", "nameWell", "introduction"]},
      {location: ["codeQuality", "nameWell", "basic", "nounsAndVerbsAsNames"]},
      {location: ["codeQuality", "nameWell", "basic", "useStandardWords"]},
      {location: ["codeQuality", "nameWell", "intermediate", "useNameExplain"]},
      {location: ["codeQuality", "nameWell", "intermediate", "notTooLongNorShort"]},
      {location: ["codeQuality", "nameWell", "intermediate", "avoidMisleadingNames"]},
    {heading: "Code Quality: Readability"},
      {subheading: "Readability", panopto: "c7eeb42d-4d9b-43c4-b178-ac2900e20610"},
      {location: ["codeQuality", "maximiseReadability", "basic", "avoidLongMethods"]},
      {location: ["codeQuality", "maximiseReadability", "basic", "avoidDeepNesting"]},
      {location: ["codeQuality", "maximiseReadability", "basic", "avoidComplicatedExpressions"]},
      {location: ["codeQuality", "maximiseReadability", "basic", "avoidMagicNumbers"]},
      {location: ["codeQuality", "maximiseReadability", "basic", "makeCodeObvious"]},
      {location: ["codeQuality", "maximiseReadability", "intermediate", "structureCodeLogically"]},
      {location: ["codeQuality", "maximiseReadability", "intermediate", "dontTripReader"]},
      {location: ["codeQuality", "maximiseReadability", "intermediate", "practiceKISSing"]},
      {location: ["codeQuality", "maximiseReadability", "intermediate", "avoidPrematureOptimizations"]},
      {location: ["codeQuality", "maximiseReadability", "intermediate", "slapHard"]},
      {location: ["codeQuality", "maximiseReadability", "advanced", "makeHappyPathProminent"]},
    {heading: "Refactoring", panopto: "006255cc-d307-4c04-abbe-ac2a006129fc"},
      {location: ["refactoring", "what"]},
      {location: ["intellij", "refactoring"]},
      {location: ["refactoring", "how"]},
      {location: ["refactoring", "when"]},
  {name: "Project Management"},
    {heading: "RCS: Reviewing pull requests"},
      {location: ["gitAndGithub", "reviewPRs"], panopto: "c001244c-01b5-4471-ab9d-ac1b0098110a"},
    {heading: "RCS: Branching"},
      {location: ["revisionControl", "branching"], panopto: "c1688fb0-ff95-462c-a736-ac0e00c93e04"},
      {location: ["gitAndGithub", "branch"], panopto: "2580eb90-e6c1-42ab-9b5b-ac0e00c93de0"},
      {location: ["gitAndGithub", "mergeConflicts"], panopto: "6de3f8b2-af7b-403a-a34f-ac0e00c97328"},
{week: "5"},
  {name: "Java"},
    {heading: "Java: Generics"},
      {location: ["cppToJava", "generics", "what"]},
      {location: ["cppToJava", "generics", "how"]},
    {heading: "Java: Collections"},
      {location: ["cppToJava", "collections", "what"]},
      {location: ["cppToJava", "collections", "arrayListClass"]},
      {location: ["cppToJava", "collections", "hashMapClass"]},
    {heading: "Java: File Access"},
      {location: ["cppToJava", "misc", "fileAccess"]},
    {heading: "Java: JAR Files"},
      {location: ["cppToJava", "misc", "jar"]},
    {heading: "Java: Varargs"},
      {location: ["cppToJava", "misc", "varargs"]},
    {heading: "Java: streams"},
      {location: ["cppToJava", "misc", "streams"]},
  {name: "Documentation"},
    {heading: "Documentation Tools"},
      {subheading: "Javadoc"},
        {location: ["documentation", "tools", "javaDoc", "what"], panopto: "46becd1e-d2bb-4a4a-ae74-ac0e00cf9d99"},
        {location: ["documentation", "tools", "javaDoc", "how"]},
  {name: "Implementation"},
    {heading: "Code Quality: Code Comments", panopto: "48728599-61b6-4c06-8fd4-ac2900d84d40"},
      {location: ["codeQuality", "commentMinimally", "introduction"]},
      {location: ["codeQuality", "commentMinimally", "basic", "dontRepeatObvious"]},
      {location: ["codeQuality", "commentMinimally", "basic", "writeToReader"]},
      {location: ["codeQuality", "commentMinimally", "intermediate", "explainWhatWhyNotHow"]},
  {name: "Requirements"},
    {heading: "Requirements: Intro"},
      {location: ["requirements", "introduction"], panopto: "88d01602-d48b-44eb-b8d1-ac2900b7398c"},
      {location: ["requirements", "nonFunctionalRequirements"]},
      {location: ["requirements", "prioritizing"]},
      {location: ["requirements", "quality"]},
    {heading: "Requirements: Gathering", panopto: "e9253486-b36d-4d7f-8044-ac2900bd46d1"},
      {location: ["gatheringRequirements", "brainstorming"]},
      {location: ["gatheringRequirements", "productSurveys"]},
      {location: ["gatheringRequirements", "observation"]},
      {location: ["gatheringRequirements", "userSurveys"]},
      {location: ["gatheringRequirements", "interviews"]},
      {location: ["gatheringRequirements", "focusGroups"]},
      {location: ["gatheringRequirements", "prototyping"]},
    {heading: "Requirements: Specifying", panopto: "37e45832-1d21-43e1-a8fa-ac2900cef5a4"},
      {subheading: "Prose"},
        {location: ["specifyingRequirements", "prose", "what"]},
      {subheading: "User Stories"},
        {location: ["specifyingRequirements", "userStories", "introduction"]},
        {location: ["specifyingRequirements", "userStories", "details"]},
        {location: ["specifyingRequirements", "userStories", "usage"]},
      {subheading: "Feature Lists"},
        {location: ["specifyingRequirements", "featureList", "what"]},
      {subheading: "Use Cases"},
        {location: ["specifyingRequirements", "useCases", "introduction"]},
      {subheading: "Glossary"},
        {location: ["specifyingRequirements", "glossary", "what"]},
      {subheading: "Supplementary Requirements"},
        {location: ["specifyingRequirements", "supplementaryRequirements", "what"]},
  {name: "Project Management"},
    {heading: "RCS: Merging PRs"},
      {location: ["gitAndGithub", "managePRs"]},
{week: "6"},
  {name: "Implementation"},
    {heading: "IDEs: Intermediate Features"},
      {location: ["ides", "debugging", "what"], panopto: "4a778a0b-e16a-4318-a1c4-ac2800e20e48"},
      {location: ["intellij", "debuggingBasic"]},
      {location: ["intellij", "productivityShortcuts"]},
    {heading: "Code Quality: Unsafe Practices"},
      {location: ["codeQuality", "avoidShortcuts", "introduction"]},
      {location: ["codeQuality", "avoidShortcuts", "basic", "useDefaultBranch"]},
      {location: ["codeQuality", "avoidShortcuts", "basic", "dontRecycleVarsOrParams"]},
      {location: ["codeQuality", "avoidShortcuts", "basic", "avoidEmptyCatchBlocks"]},
      {location: ["codeQuality", "avoidShortcuts", "basic", "deleteDeadCode"]},
      {location: ["codeQuality", "avoidShortcuts", "intermediate", "minimiseVariableScope"]},
      {location: ["codeQuality", "avoidShortcuts", "intermediate", "minimiseCodeDuplication"]},
  {name: "Quality Assurance"},
    {heading: "Developer Testing"},
      {location: ["testing", "testingTypes", "developerTesting", "what"]},
      {location: ["testing", "testingTypes", "developerTesting", "why"], panopto: "abc1422b-7c14-47a4-b769-ac0e00e022f1"},
    {heading: "Unit Testing", panopto: "35868c76-721f-4cb4-93f5-ac0f00ccd405"},
      {location: ["testing", "testAutomation", "usingTestDrivers"]},
      {location: ["testing", "testAutomation", "tools"]},
      {location: ["testing", "testingTypes", "unitTesting", "what"]},
      {location: ["cppToJava", "junit", "basic"]},
{week: "7"},
  {name: "Project Management"},
    {heading: "SDLC Process Models: Basics"},
      {location: ["processModels", "introduction", "what"]},
      {location: ["processModels", "introduction", "sequentialModels"]},
      {location: ["processModels", "introduction", "iterativeModels"]},
    {heading: "Continuous Integration/Deployment"},
      {location: ["integration", "introduction", "what"]},
      {location: ["integration", "buildAutomation", "what"]},
      {location: ["integration", "buildAutomation", "continuousIntegrationDeployment"]},
    {heading: "Project Mgt: Workflows", panopto: "050c0949-853c-4b7d-b1fb-ac3700d88202"},
      {location: ["revisionControl", "forkingWorkflow"]},
      {location: ["gitAndGithub", "forkingWorkflow"]},
      {location: ["revisionControl", "drcsVsCrcs"]},
      {location: ["revisionControl", "featureBranchFlow"]},
      {location: ["revisionControl", "centralizedFlow"]},
{week: "8"},
  {name: "Design"},
    {heading: "Design: Fundamentals", panopto: "9c7ce7f2-2b96-4e86-a9b1-ac3700bab81c"},
      {subheading: "Abstraction"},
        {location: ["designFundamentals", "abstraction", "what"]},
      {subheading: "Coupling"},
        {location: ["designFundamentals", "coupling", "what"]},
        {location: ["designFundamentals", "coupling", "how"]},
        {location: ["designFundamentals", "coupling", "types"]},
      {subheading: "Cohesion"},
        {location: ["designFundamentals", "cohesion", "what"]},
        {location: ["designFundamentals", "cohesion", "how"]},
    {heading: "Design Principles: SoC, SRP"},
      {location: ["principles", "separationOfConcernsPrinciple"], panopto: "e2b68479-4455-4c13-a154-ac4400f03453"},
      {location: ["principles", "singleResponsibilityPrinciple"], panopto: "f7d3b1a6-89f3-4781-80e6-ac4400f03413"},
  {name: "Project Management"},
    {heading: "Project Mgt: Scheduling and Tracking", panopto: "e4bdedb1-34a1-4da1-9b57-ac390047588e"},
      {location: ["projectPlanning", "milestones"]},
      {location: ["projectPlanning", "buffers"]},
      {location: ["projectPlanning", "issueTrackers"]},
      {location: ["projectPlanning", "workBreakdownStructure"]},
      {location: ["projectPlanning", "ganttCharts"]},
      {location: ["projectPlanning", "pertCharts"]},
      {location: ["teamwork", "teamStructures"]},
  {name: "Quality Assurance"},
    {heading: "Other QA Techniques"},
      {location: ["qualityAssurance", "introduction", "what"]},
      {location: ["qualityAssurance", "introduction", "validationVsVerification"]},
      {location: ["qualityAssurance", "codeReviews", "what"]},
      {location: ["qualityAssurance", "staticAnalysis", "what"]},
      {location: ["qualityAssurance", "formalVerification", "what"]},
    {heading: "Testing: Intermediate Concepts"},
      {location: ["testing", "introduction", "testability"]},
      {location: ["cppToJava", "junit", "intermediate"]},
      {location: ["testing", "tdd", "what"], panopto: "6c561949-dcbb-40bc-b731-ac4400edca2a"},
{week: "9"},
  {name: "Design"},
    {heading: "Design Patterns"},
      {subheading: "Introduction", panopto: "5d44830a-a6db-44d9-b755-ac4c00db1817"},
        {location: ["designPatterns", "introduction", "what"]},
        {location: ["designPatterns", "introduction", "format"]},
      {subheading: "Singleton pattern", panopto: "3496baa6-a3a4-408b-b6a9-ac4c00dae39f"},
        {location: ["designPatterns", "singleton", "what"]},
        {location: ["designPatterns", "singleton", "implementation"]},
        {location: ["designPatterns", "singleton", "evaluation"]},
      {subheading: "Facade pattern", panopto: "652f61d4-6020-4203-b075-ac4c00dae377"},
        {location: ["designPatterns", "facade", "what"]},
  {name: "Implementation"},
    {heading: "Logging", panopto: "2c02102e-1a30-4d51-aab6-ac3000c5553d"},
      {location: ["errorHandling", "logging", "what"]},
      {location: ["errorHandling", "logging", "how"]},
    {heading: "Assertions"},
      {location: ["errorHandling", "assertions", "what"], panopto: "cc9a700d-d611-4519-a4e1-ac2a00612a33"},
      {location: ["errorHandling", "assertions", "how"]},
      {location: ["errorHandling", "assertions", "when"]},
  {name: "Quality Assurance"},
    {heading: "Testing: Test Coverage", panopto: "7d400e4f-4a02-4a38-b188-ac4400ed259b"},
      {location: ["testing", "testCoverage", "what"]},
      {location: ["testing", "testCoverage", "how"]},
{week: "10"},
  {name: "Quality Assurance"},
    {heading: "Types of Testing"},
      {subheading: "Unit Testing: continued"},
        {location: ["testing", "testingTypes", "unitTesting", "stubs"]},
        {location: ["testing", "dependencyInjection", "what"], panopto: "16c8b473-9e33-4946-876e-ac4400ed2605"},
        {location: ["testing", "dependencyInjection", "how"]},
      {subheading: "Integration Testing"},
        {location: ["testing", "testingTypes", "integrationTesting", "what"], panopto: "8b61d981-7a3e-486d-b621-ac4400ed5393"},
        {location: ["testing", "testingTypes", "integrationTesting", "how"], panopto: "8b23e595-60f9-4a84-8fc5-ac4400ed25d4"},
      {subheading: "System Testing"},
        {location: ["testing", "testingTypes", "systemTesting", "what"]},
        {location: ["testing", "testAutomation", "testingGuis"], panopto: "03388690-1d62-4649-aa4f-ac4400ed7085"},
      {subheading: "Acceptance Testing"},
        {location: ["testing", "testingTypes", "acceptanceTesting", "what"]},
        {location: ["testing", "testingTypes", "acceptanceTesting", "acceptanceVsSystemTesting"], panopto: "31357df3-4a39-4922-adc1-ac4400ed257e"},
      {subheading: "Alpha/Beta Testing"},
        {location: ["testing", "testingTypes", "alphaBetaTesting", "what"]},
    {heading: "Test Cases: Intro"},
      {location: ["testCaseDesign", "introduction", "what"], panopto: "bd513fd6-8ccb-4bb3-8467-ab8d009a8de0"},
      {location: ["testing", "testingTypes", "exploratoryVsScriptedTesting", "what"]},
      {location: ["testing", "testingTypes", "exploratoryVsScriptedTesting", "when"], panopto: "63fbdba7-386c-4b2b-bb70-ac4400eda9fc"},
      {location: ["testCaseDesign", "introduction", "positiveVsNegative"]},
      {location: ["testCaseDesign", "introduction", "blackVsGlass"], panopto: "8221a124-fe08-4c48-8a72-ab8d00aa53d3"},
    {heading: "Equivalence Partitioning"},
      {location: ["testCaseDesign", "equivalencePartitions", "what"], panopto: "59a122d2-7170-4aea-9888-ab8d00b850ed"},
      {location: ["testCaseDesign", "equivalencePartitions", "basic"], panopto: "83001c05-69fb-4322-b571-ab8d00cd4337"},
      {location: ["testCaseDesign", "equivalencePartitions", "intermediate"]},
    {heading: "Boundary Value Analysis"},
      {location: ["testCaseDesign", "boundaryValueAnalysis", "what"], panopto: "357faa3a-c24a-4ff5-ac10-ab8e00baf4f5"},
      {location: ["testCaseDesign", "boundaryValueAnalysis", "how"], panopto: "0edaf584-6ba5-4b05-8f98-ab8e00bfc897"},
{week: "11"},
  {name: "Documentation"},
    {heading: "Writing Developer Documents", panopto: "6b9a60d3-ad4f-4177-b4db-ac4b00d01426"},
      {location: ["documentation", "introduction", "what"]},
  {name: "Design"},
    {heading: "Design: Models"},
      {location: ["design", "introduction", "what"]},
      {location: ["modeling", "introduction", "what"]},
      {location: ["modeling", "introduction", "how"]},
    {heading: "Class/Object Diagrams: Basics", panopto: "03c5a0f1-9354-4d83-8229-acbf00b4b3dc"},
      {location: ["modeling", "modelingStructures", "ooStructures"]},
      {location: ["modeling", "modelingStructures", "classDiagramsBasic"]},
      {location: ["modeling", "modelingStructures", "objectDiagrams"]},
      {location: ["uml", "miscellaneous", "objectVsClassDiagrams"]},
      {location: ["uml", "classDiagrams", "associationsAsAttributes", "what"]},
      {location: ["uml", "notes", "notes"]},
    {heading: "Class/Object Diagrams: Intermediate", panopto: "9e6f5f1a-5596-498e-86f6-ac1b00e43a38"},
      {location: ["modeling", "modelingStructures", "classDiagramsIntermediate"]},
{week: "12"},
  {name: "Design"},
    {heading: "Sequence Diagrams: Basics"},
      {location: ["modeling", "modelingBehaviors", "sequenceDiagramsBasic"], panopto: "7aefe728-a7ad-4871-86b8-ac3000bcf7d1"},
    {heading: "Sequence Diagrams: Intermediate"},
      {location: ["modeling", "modelingBehaviors", "sequenceDiagramsIntermediate"], panopto: "f76680f0-7375-431b-a15a-ac3000bcf7a5"},
      {location: ["uml", "sequenceDiagrams", "parallelPaths"]},
      {location: ["uml", "sequenceDiagrams", "referenceFrames"]},
{week: "13"}
]%}

{% set weeks_with_no_topics = ["1", "13"] %}
