@startwbs
skinparam backgroundcolor transparent
+ <b><color:red>100</color></b> marks
 + Individual Project (iP): <b><color:red>10</color></b> marks
 + Team Project (tP): <b><color:red>45</color></b> marks
  + Design:<b><color:red>5</color></b> marks
  + Implementation: <b><color:red>10</color></b> marks
  + Documentation: <b><color:red>10</color></b> marks
  + QA: <b><color:red>10</color></b> marks
  + Project Management: <b><color:red>10</color></b> marks
 + Exam: <b><color:red>40</color></b> marks
  + Part I (MCQ): <b><color:red>20</color></b> marks
  + Part II (Essay): <b><color:red>20</color></b> marks
 + Participation: <b><color:red>5</color></b> marks
@endwbs